### ISSUE TITLE
Suggestion: Gran Turismo 1 PAL

### ISSUE THREAD

**Issue by iamgreaser** [socram8888/tonyhax#1]
This one's likely to be somewhat nasty as it requires a save which unpacks to 16 sectors, so you have to loop the last physical sector of the save onto itself... and it makes it somewhat impossible to deal with in the PS1 BIOS shell. It's probably best to deploy this on a microcontroller rather than a regular PS1 memory card.

I think I found this one in 2019, so it's going to take a while for me to piece this together. Also please let me know if any of this is wrong.

The kind of save file I use for this is a car settings save. For PAL this is "BESCES-00984CS".

The method I use to activate the payload if I recall correctly:

- Enter Gran Turismo mode.
- Buy a used car.
- Go Race -> Time Trial -> any track will do but Autumn Ring Mini is probably the fastest... but it doesn't matter because it takes a loooooong time to load a 16-sector save.
- Load your car settings.
- Eventually you will hear a buzz sound effect indicating that your settings failed to load correctly... and your payload should run.

So let's bring up some pointers from my notes I had to hunt down.

- 0x801D2E2C: Start of where the memory card save buffer is in RAM. This is your overall load address.
- 0x801F22D8: Function pointer. When the save inevitably fails its CRC check, it jumps to whereever this points to.

This means you need your pointer at 0x1F4AC bytes into the save, or 0x14AC bytes into the last sector of your 16-sector save which you have looping back onto itself.

NTSC-U should have something similar.

**Comment by socram8888** [comment]
Hello. Sorry for the delay but these last day I've been too busy crunching to fix the bugs and quirks that were present in the code base.

Regarding that game, if it requires something so complex I'm not sure if it'd be IMO worth supporting. The key features of the other games is that you don't need any ability with electronics, just an average knowledge about console hacking. If this game requires a microcontroller, my opinion is that at that point you might as well chip the console.

With that said, I'll try to check how feasible is to exploit this game as soon as I'm done with the backlog of other games. This is one that could be really interesting to do so since according to Wikipedia it's the PS1 that sold the most.

Marcos

**Comment by FMecha** [comment]
> * Go Race -> Time Trial -> any track will do but Autumn Ring Mini is probably the fastest... but it doesn't matter because it takes a loooooong time to load a 16-sector save.

For this step, you can also use Machine Test -> 0-400 since it's way shorter and thus faster.

**Comment by socram8888** [comment]
Since this is too convoluted and there are enough games already I'm closing it.
