### ISSUE TITLE
Spider-Man wont boot on SPCH-1001 but boots on SPCH-101

### ISSUE THREAD

**Issue by WinterSith** [socram8888/tonyhax#114]
**tonyhax version**:  1.4.3
**Installation method**: ps2 ulaunchelf
**Entry point game**: cool boarders 4
**Console model**: SPCH 1001 will not run disc but SPCH 101 will run same disk
**Integrity check**: yes for both
**BIOS version**: SPCH 101 bios = v4.5
**Target game**:  SLUS-00875 | SPIDER-MAN

**Bug explanation**: SLUS-00875, SPIDER-MAN will not run on my SPCH 1001, it gets stuck on starting. However, my SPC-101 will run the same spider man disc.  SPCH 1001 has successfully run other games via tonyhax 1.4.3 and cool boarders 4

**Comment by socram8888** [comment]
Have you tried with other games? To rule out a dying laser drive. Old units AFAIK are notorious for having the drives made with plastic that fail after some time due to heat from the PSU.

**Comment by alex-free** [comment]
> Have you tried with other games? To rule out a dying laser drive. Old units AFAIK are notorious for having the drives made with plastic that fail after some time due to heat from the PSU.

Excellent news, this is not a software issue. My SCPH-1001 using the latest Tonyhax v1.4.4 Boot CD via CD Player Swap Trick boots Spider-Man as expected.

I think the issue this indivisual was having is an iffy CD drive. Just because one game works ok on your console, does not mean every game will work as expected if the CD drive is having trouble reading discs.

CD-Rs are less reflective then pressed CD-ROM discs. The earliest consoles not only shipped with an inferior drive mechanism made of warpable plastic on the sled rails, they also have a CD servo that is much more intolerant of read errors/slight miscalculations in seeking due to worn down lubrication, see: https://alex-free.github.io/unofficial-ps1-cd-drive-service-manual/ for more on that.

Anyways, Spider-Man immediately starts playing an FMV after booting, which will for sure cause issues if your CD drive is not working as well as it should be. I believe this person is simply encountering a disc read error when the game tries to start playing the opening FMV.
