### ISSUE TITLE
DDR 3rd and 4th mix stuck at now loading screen 

### ISSUE THREAD

**Issue by datboi2008** [socram8888/tonyhax#133]
Before opening this kind of issue, please ensure:
 - Are you using a compatible console version?
 - Are you using CD-R media, and not CD-RW?
 - Did you copy all the files in the expected format to the memory card?

**tonyhax version**: Which version are you running? Please ensure you are running the latest stable, or a newer beta.
**Installation method**: How did you get tonyhax on the memory card?
**Entry point game**: Which game are you using to launch tonyhax?
**Console model**: Console product code, written on the bottom of the unit, such as "SCPH-7502"
**Integrity check**: If it boots, does the built-in integrity check succeed?
**BIOS version**: If you can get to boot, which version of the BIOS does it report?
**Target game**: If the bug happens when launching a game, what's its name and game code? Example: "Spyro 3 (SCES-02835)"

**Bug explanation**:
Details:
![Dance Dance Revolution 3rd MIX , Playstation version - YouTube and 2 more pages - Personal - Microsoft​ Edge 7_22_2022 10_27_52 PM](https://user-images.githubusercontent.com/100240588/180587225-94fb1492-45d7-4fbe-ad94-e9de581db47e.png)

Tonyhax version: 1.4.3
Ps1 version: SCPH-7501 (NTSC-U/C)
Ps1 Bios version: v1.4
Game used to run tonyhax: THPS3 (SLUS-01419)
I got Tony Hax onto my memory card using a ps2 with UlaunchElf
I followed this guide: https://www.youtube.com/watch?v=01gVgTQLP9U
Games with Problems:
DDR 3rd mix (have not tried 3rd mix plus or 4th mix but same engine so im guessing same issue)

**Comment by alex-free** [comment]
Bumping this, as it seems to be the exact same issue as https://github.com/alex-free/tonyhax/issues/10 . DDR Best Hits Japan is getting stuck at the same exact loading screen in the same way. Reproduced by me with a stock SCPH-1001. Reproduced by @M4x1mumReZ with a SCPH-7502.

**Comment by socram8888** [comment]
Have you tried on an emulator? I am working so cannot at the moment.

**Comment by alex-free** [comment]
> Have you tried on an emulator? I am working so cannot at the moment.

Unreproducible on emulation using DuckStation+ Boot CD, only on real hardware.

**Comment by M4x1mumReZ** [comment]
The same can also be said for my stock SCPH-1002, so this must be an anti-piracy issue I suppose.

**Comment by M4x1mumReZ** [comment]
The only way you could defeat it is to maybe eliminate the routine altogether.

**Comment by socram8888** [comment]
How are you booting into tonyhax?

**Comment by M4x1mumReZ** [comment]
I've booted into Tonyhax International via both cheat cartridge and boot CD with swap trick.

**Comment by M4x1mumReZ** [comment]
Used two models for this: SCPH-1002 and SCPH-7502.

**Comment by alex-free** [comment]
> I've booted into Tonyhax International via both cheat cartridge and boot CD with swap trick.

I have confirmed this same issue is present in Tonyhax v1.4.4 AND Tonyhax International. I used the Tonyhax v1.4.4 Boot CD via CD Player Swap Trick on my SCPH-1001.

**Comment by socram8888** [comment]
Yup, will certainly do.

**Comment by alex-free** [comment]
> Yup, will certainly do.

I created a fork of CDRDAO that forces byte-swapping CD audio files (which is required for CDRDAO to burn **any kind of CD containing CD audio** correctly on every system I've tested, from Mac back in the day to Linux right now) **in every write mode**. This means that I can burn with the generic-mmc-raw driver and the CD audio will also work. 

The actual official CDRDAO is not capable of burning in raw mode AND byteswapping the CD audio files. The --swap argument or even explicitly specifiying '--driver generic-mmc-raw:0x20000' is completely ignored by the official CDRDAO. You can only use the swap options (and have them applied to the disc burned) if you use the generic-mmc driver.

I went ahead and hacked on cdrdao's source code a bit. I got it to force byte-swapping of the CD audio samples in my own fork, so finally everything works. Keep in mind that if you don't have CDRDAO treat the audio as byteswapped, you get insanely load static/white noise instead of the intended CDDA music). See my original dilemma? 

Well finally everything works and I can proceed to test out this game as well. I can finally make a proper DDR 2nd Remix burn from Linux using just open source software.

Here's my fork by the way:
https://github.com/alex-free/cdrdao

Here's my 'hacks on cdrdao' to get this working:
https://github.com/alex-free/cdrdao/commit/6e544d25de0c61b294e2733ae012f4b3ebf3e0fe

Please make sure the website specifies this fork, because the official CDRDAO will produce invalid CD audio tracks burned to the disc in the wrong byte order, which causes static/white noise.

**Comment by alex-free** [comment]
I have confirmed that by using [my cdrdao fork](https://github.com/alex-free/cdrdao) with the generic-mmc-raw driver to burn each CD-R, all of the below games now work as expected on my stock SCPH-1001 using the Tonyhax v1.4.4 Boot CD via CD Player Swap Trick:

 - Dance Dance Revolution Best Hits.
 - Dance Dance Revolution 3rd Mix.
 - Dance Dance Revolution 4th Mix.

Proving the EDC check is what causes this (just like https://github.com/socram8888/tonyhax/issues/121#issuecomment-1341365357) , and that it can be bypassed with known burning methods.

**Comment by krystalgamer** [comment]
great work @alex-free 
do you have any plans in upstreaming your patches?

**Comment by alex-free** [comment]
> great work @alex-free do you have any plans in upstreaming your patches?

Hey, didn't you do the tekken 3 exploit stuff? I got Tekken 2 and Tekken 3 exploits into tonyhax international because of your previous work. https://alex-free.github.io/tonyhax-international#save-game-exploit . Thanks for that.

My approach with cdrdao was a 'brute-force I know how it needs to function internally' type modification. It's probably too hacky as-is for upstream. I was originally going for a more proper patch set but it got complicated.

**Comment by krystalgamer** [comment]
glad someone used it :D

anyways it's great to start for a better CDDA on cdrdao

**Comment by M4x1mumReZ** [comment]
I might come up with some exploitable saves in the near future, I'm busy right now.

**Comment by alex-free** [comment]
So Dance Dance Revolution Japan and USA versions (the 1st DDR game)  have the APv1 style detection (that only triggers if you have a non-stealth modchip spamming the SCEX code). This might be bypassed already in the current Tonyhax, have not tested on real hardware for that. But more importantly, they also have the EDC check at sector 12 just like the newer DDR games.

You know, it wouldn't be that hard to simply see if the EDC is invalid in each sector, and then report which sector has invalid EDC data indicating an EDC check. I'll make a program which can detect this (using proper clean game rips as input) soon, maybe I'll integrate such functionallity into https://alex-free.github.io/aprip .

**Comment by alex-free** [comment]
> glad someone used it :D
> 
> anyways it's great to start for a better CDDA on cdrdao

You inspired me to go back to CDRDAO and figure out the actual bug that was causing this. I threw away my hacky changes and actually figured out the bug. 

[My CDRDAO Fork](https://github.com/alex-free/cdrdao) **does not ignore the --swap argument when using the generic-mmc-raw driver, the official CDRDAO does however**. The --swap argument is required for seemingly most, but not all PSX game rips which contain CD audio. Essentially, if you get static when playing back a CD with audio tracks that you burned with CDRDAO, the audio samples need to be 'byte-swapped' when sent to the CD drive during the burn. You can do this with the official CDRDAO with the --swap option and the generic-mmc driver, but you couldn't before with the generic-mmc-raw driver due to a bug I did find.

I did do a [pull request](https://github.com/cdrdao/cdrdao/pull/11) for the official CDRDAO. Thanks for pushing me to look at this properly again when I had more time.

**Comment by M4x1mumReZ** [comment]
I need help building your CDRDAO fork to work with Linux. Currently, I'm using Linux Mint.

**Comment by alex-free** [comment]
> I need help building your CDRDAO fork to work with Linux. Currently, I'm using Linux Mint.

What issue are you having?

**Comment by M4x1mumReZ** [comment]
> > I need help building your CDRDAO fork to work with Linux. Currently, I'm using Linux Mint.
> 
> What issue are you having?

Compiling the fork under Linux.
