### ISSUE TITLE
Using Cool boarders 4 in a PsOne, sometimes doesn't load

### ISSUE THREAD

**Issue by Ruthless95** [socram8888/tonyhax#52]
Before opening this kind of issue, please ensure:
 - Are you using a compatible console version? Yes
 - Are you using CD-R media, and not CD-RW? Yes
 - Did you copy all the files in the expected format to the memory card? Yes

**tonyhax version**: Which version are you running? Please ensure you are running the latest stable, or a newer beta. 1.2.2
**Installation method**: How did you get tonyhax on the memory card? freemcboot, ulaunch
**Entry point game**: Which game are you using to launch tonyhax? Cool Boarders 4
**Console model**: Console product code, written on the bottom of the unit, such as "SCPH-7502" PsOne & Ps2 schp-39004
**Integrity check**: If it boots, does the built-in integrity check succeed? Yes
**BIOS version**: If you can get to boot, which version of the BIOS does it report?
**Target game**: If the bug happens when launching a game, what's its name and game code? Example: "Spyro 3 (SCES-02835)"

**Bug explanation**:
Sometimes the exploit freezes in the Initializing CD, with original games and burned CD-R, I don't know if I'm doing something wrong. And a noob question, this works with ps2 games in the ps2?

**Comment by Goldanas** [comment]
I am using a PS2 with Cool Boarders 4, and generally I only see issues of getting stuck at Initializing Disc if the system is having trouble actually reading the CD-R disc, which these models of PS2 are notorious for.

CDs are very thin and light, and the disc spindle may spin freely and not actually be able to read the disc. To help with this, grab some masking tape (tape that has a bit of texture on the top) and just apply it to the top of the CD where the label would go, as close to the hole as possible on either side without covering it up. This will give it some weight, and will also help the top magnetized holder grip the disc better so that it doesn't slip on the spindle. Just keep an ear out for any loud odd noises from the drive, and you'll know if there's a problem.

If the above doesn't help, you may need to open up the PS2 and clean up the laser assembly if it's having other disc read errors, which I would recommend looking up other guide videos for this. I did a full clean-up of my PS2 and it's reading discs like a champ now.

Also, this is only for PS1 games, so if you're trying to play burned PS2 games, it won't work.

**Comment by Ruthless95** [comment]
> 
> 
> I am using a PS2 with Cool Boarders 4, and generally I only see issues of getting stuck at Initializing Disc if the system is having trouble actually reading the CD-R disc, which these models of PS2 are notorious for.
> 
> CDs are very thin and light, and the disc spindle may spin freely and not actually be able to read the disc. To help with this, grab some masking tape (tape that has a bit of texture on the top) and just apply it to the top of the CD where the label would go, as close to the hole as possible on either side without covering it up. This will give it some weight, and will also help the top magnetized holder grip the disc better so that it doesn't slip on the spindle. Just keep an ear out for any loud odd noises from the drive, and you'll know if there's a problem.
> 
> If the above doesn't help, you may need to open up the PS2 and clean up the laser assembly if it's having other disc read errors, which I would recommend looking up other guide videos for this. I did a full clean-up of my PS2 and it's reading discs like a champ now.
> 
> Also, this is only for PS1 games, so if you're trying to play burned PS2 games, it won't work.

This problem doesn't happen in my ps2 but yes in Psone, the burned CD-R stops spinning in the PsOne but in the Ps2 reads fine.

**Comment by Ruthless95** [comment]
> 
> 
> Please try with 1.2.3 which does some extra reinitialization with the drive

Didn't work

**Comment by socram8888** [comment]
Then it's probably that either the media is flaky, the laser on the PS1 is, or a mix of the previous.
