### ISSUE TITLE
Possible support for modded games? 

### ISSUE THREAD

**Issue by duke1102** [socram8888/tonyhax#59]
**Game name**: Yu-Gi-Oh! Forbidden Memories - 5 Card & 15 Card Drop Mod
**Game code**: SLUS-01411
**Executable hash**: MD5, both are the same: 368dc397ef49faa6cc37aac8f5894366
SHA1: 2a4d40ccb2e5a42b2abdb13f9e281089d762e600

Initial support for the base game was added here: https://github.com/socram8888/tonyhax/commit/7f9e6429c997fa09d49ada9e89111cbf01bd613c

The mod executable checksum differs from the original, since there is some small logic added in to it.  
I'd create a patch to add the support myself, but I need to know first how to correctly get the hash in hex format from md5/sha (line 42: `.hash = 0x896FF9BA,`)...  

It's probably super simple, but I can't come up with a way and don't feel like researching that much, so I'd appreciate if you can describe the procedure to me! I also wonder how the copy protection check works in detail, wouldn't it just be possible to remove the check from the executable file in case of modded games, or would the console still reject the game disc?  

**Anyways, to get the to actual topic of this issue:**  

Would it be possible to implement a feature to tonyhax, where you can **add in support for game mods,** without having to modify the source code every time? My idea would be to have like a config file where you first enter the original base game with it's executable, hash and copy protection address and then specify several mods of the game with their according executable hash. Then once you boot up a game it checks the executable name against that config and looks for the hash to see if it is a mod.  
My knowledge of PS1 modding and coding is very limited though, so what I describe might be a good idea at first, but I'm not sure if it's as easy as I picture in my mind.  

Anyways, thanks for now and good work on this softmod!

**Comment by socram8888** [comment]
I'm closing this since I don't think adding support for modded games is really needed - I honestly don't see why would you mod the game but keep the antipiracy on. It's one of the very first things I'd disable if I modded a game.

A generic way of applying manually the patches that tonyhax adds on the fly is as follows:
 - Extract the main executable from the ISO/BIN/CUE (generally, has the same name as the game code - in this case, it would be a file in the root of the disc called SLUS_014.11)
 - Open it into an hexadecimal editor (I'd suggest HxD).
 - In these executables there's first a 0x800 byte header that indicates several stuff. Important for us is at 0x18, where a 4 bytes specify the "load address" in [little endian](https://en.wikipedia.org/wiki/Endianness) (where the executable needs to be loaded in the console's RAM), generally "00 00 01 80". This would be 0x80010000.
 - Open the [patches.c](https://github.com/socram8888/tonyhax/blob/master/patcher.c) file where codes are specified, and find your game. For YuGiOh US there's a single patch that reads:
   ```
	{
		// Nuke the call to the check antipiracy function
		.offset = 0x80043AFC,
		.size = 20,
		.flags = FLAG_LAST | FLAG_NOP,
	}
    ```
   0x80043AFC is the address where we have to insert the data. This data consists of just zeros (indicated by FLAG_NOP), and we have to **overwrite** (not insert) 20 of them (indicated by the size field)

We have all the data to patch the game now: if the patch has to be made at 0x80043AFC and the executable is loaded at 0x80010000, we have to overwrite with 20 zeros the data inside the executable file at 0x80043AFC (patch address) - 0x80010000 (load address) + 0x800 (EXE header size) = 0x342FC.

If we then go to address 0x342FC of the EXE file, overwrite the data there with 20 zero bytes, we would've nuked the antipiracy.

**Comment by socram8888** [comment]
A small note I want to add about this issue: since v1.4, tonyhax __should__ run modded and unpatched games just fine.
