### ISSUE TITLE
Crash Bandicoot 2: Cortex Strikes Back - Blue screen freeze on PS2 slim

### ISSUE THREAD

**Issue by faissaloo** [socram8888/tonyhax#63]
**tonyhax version**: 1.3
**Installation method**: wLaunchELF
**Entry point game**: Crash Bandicoot 2 Cortex Strikes Back
**Console model**: SCPH-75003
**Target game**: BESCES-0096700765150

**Bug explanation**:
Previously when running Tonyhax on a PS2 Slim the exploit would succeed, it just wouldn't let me load anything cus of 'unsupported region', however now when I load it I just get a blue screen and it freezes

**Comment by socram8888** [comment]
Thanks for the report! This new version uses a unusual BIOS call which, although supported on the PS1, might be stubbed on the PS2 since to my knowledge no commercial game ever used it.

I am gonna attempt to obtain the list of supported BIOS calls on the PS2 and see how to sort this out.

Meanwhile, could you please give a try with this save file instead? It will display a myriad of colors while booting, one after every BIOS call, so if it gets stuck anywhere it would be much easier to debug: [entrypoints.zip](https://github.com/socram8888/tonyhax/files/6330870/entrypoints.zip)

**Comment by faissaloo** [comment]
That save file seems to work fine

**Comment by socram8888** [comment]
Perfect, thanks for testing it out. I'll release a 1.3.1 tonight with that hotfix.

**Comment by socram8888** [comment]
I've just released v1.3.1 which fixes this issue: https://github.com/socram8888/tonyhax/releases/tag/v1.3.1

It's the same entry point as the one I sent you minus the flashing colors, so there's no need to update for you.
