### ISSUE TITLE
The Legend of Dragoon (U) (SCUS-94491)

### ISSUE THREAD

**Issue by socram8888** [socram8888/tonyhax#83]
**tonyhax version**: v1.3.3
**Game name**: The Legend of Dragoon
**Game code**: SCUS-94491
**Executable hash**: ?
**Triggered at**: ?
**Is the console chipped?**: Irrelevant

Add support for the NTSC-U of this game, as requested on [GBAtemp](https://gbatemp.net/threads/tonyhax-is-a-new-softmod-backup-loader-for-the-playstation-1.584717/page-17#post-9470391)

**Comment by DarthMotzkus** [comment]
Hi @socram8888, thanks for looking at this antipiracy auto-patch to Legend of Dragoon (U).
I might add to it, i've tested today the other discs, and all of them has the anti-modchip screen after boot. 
Here are the game discs IDs:
Disc 1: SCUS-94491
Disc 2: SCUS-94584
Disc 3: SCUS-94585
Disc 4: SCUS-94586

Hope it helps. Stay safe.

**Comment by socram8888** [comment]
[tonyhax-v1.3.5b.zip](https://github.com/socram8888/tonyhax/files/6510922/tonyhax-v1.3.5b.zip)

Hello. It turns out this task was super easy: the four discs share the same executable so only had to patch one to have all of them fixed.

Please try it and let me know how it goes.

**Comment by DarthMotzkus** [comment]
Hi.
Tested with Brunswick bowling 2 save exploit and 1.3.5b tonyhax loader in my MC and unfortunately, the anti-mod screen still happens. I can't test via FPSXB+Tonyhax hack because of the freeze situation i mentioned on GBATemp: 
https://gbatemp.net/threads/tonyhax-is-a-new-softmod-backup-loader-for-the-playstation-1.584717/page-17#post-9478129
Dunno if you patched only the FPSXB hack to anti-mod screen of Dragoon thou.

**Comment by DarthMotzkus** [comment]
Well, i've managed to format my MC via PSX Hacker Kit, and reflashed it with the 1.3.5b FPSXBoot+Tonyhax .mcd image you provided, and no juice too, the anti-mod screen keeps showing up in all discs. Here: 
https://1drv.ms/u/s!An7j7EnH_sT9gpwsk7yVMuZACI4txQ?e=WwVPTY
those .bin and .cue Dragoon discs i'm using, i uploaded the 4 discs in a .zip file on my drive. Let me know if you managed to pass the modchip screen with them.
Tks!

**Comment by socram8888** [comment]
Mmm the checksums for your discs don't match that of the redump list: http://redump.org/disc/153/

May I ask where this images came from? The executables look a lot like the official ones but have extensive modifications, so could this be a v1.1 that's not known to exist elsewhere?

**Comment by DarthMotzkus** [comment]
I've downloaded on vimm's lair. Could be because of the mods, I thought the anti-mod patch was a specific binary code in the .exe file of the game you can change via HEXEDIT or anything like that, that's why i not mention the mods earlier (some patches to correct xp and other things).
My bad 🤦🏼‍♂️.

Source clean game: 
https://vimm.net/vault/5971

Hacks i've applied: 
https://www.romhacking.net/hacks/4072/
https://www.romhacking.net/hacks/4347/
https://www.romhacking.net/hacks/4360/

Utility to apply those hacks:
https://www.romhacking.net/utilities/1445/

There's another source i found with more hacks applied to if you want to check, for try to patch too, it is in CDROMANCE:

https://cdromance.com/psx-iso/the-legend-of-dragoon-bugfix-undub/?__cf_chl_jschl_tk__=ea2ed9088223ae4c0658ab94b8bab69f50e6f1dc-1621514336-0-Afmizccxu-dQmZd-P-wuHw2Z1N1OksZOv3FMlGMvH976sqh2ULvgrg3Lbt9s74vgUMtsRrvzUz_grhOFnwKivPXts2Kr1-g4npZvcTiktY5GFwz83oR5If3txEwyn2hozWJOrgSSTWrckIzk5ASsFlMW2zDjNderQincfd3ztU3lSmaBXnB8MriIVt4geFzUGNdspA76bk1zje1aDFedxrAtpj0Iao-cyJBlHIgwwjtJhEaH6NOU29993El88FVmBjg5iPhhxH-vvzJOxsQ5USjC5tlme_8CEsirKezCJBdXI63mcoylnBWDDnUYRiNx4MhrYMMfdXCvL-EiPJ7VOTBiemFiW4x5OmyUewW7lvkw8rNxSvrBiVH_A0gZMWm562N0Izq4h3xh0XDtBSH6AM7A8-6vAylEwQ_n608lQkMSt8HxwGi6h1q69UbTUZWn2_77_ZRSGLH6p8vd9L9NOAPwEXZjx_PmUHpMvbNJw2wxTPnqD7b6z6jmu40epJii2EKR0z2HbcHshkG1eazwxTQ

I think it's the same hacks i had applied, and another undub version, unfortunately without subtitles 🥲.

Let me know if you manage to patch any of those hacked versions, i'll be much appreciated.
And again, so sorry for not mention the hacks earlier, i really thought they have nothing to do about anti-mod screen patching process.

**Comment by socram8888** [comment]
Mmm yeah the checksum of the executable is used to detect which game it is.

It's the only reliable alternative I could think of, as the executable name is not (some older games have an executable called PSX.EXE, which makes impossible to use that to detect the game), neither is the product code (as game revisions v1.1 etc share the same product code but have different executables).

Given this is a hacked version I am not gonna add an entry for that in the patcher, as this antimodchip patching is just a convenience if you want to play with a clean version - if you're using a modded one, you might as well want to mod it to remove said protection.

If you want to mod the game to remove the protection, it's just a matter of editing the main excutable (the SCUS_XXX.XX file) and zero 12 bytes starting at offset 0x3741C.
![imagen](https://user-images.githubusercontent.com/515068/118981511-ec2cdd80-b969-11eb-9cfa-0d57b6c5323e.png)

**Comment by DarthMotzkus** [comment]
Can you help me how to do that? I manage to zero all the offset you showed selectec in the screenshot above, saved and substitute the original .exe into game .bin file, save as .iso and burn it, but the screen still happens.
Or if it's possible can you edit the .exe of the 4 discs for me? So i'll just need to put them back on the disc image and burn it again... thank you!

**Comment by DarthMotzkus** [comment]
Here are all .exe in zip file:
https://1drv.ms/u/s!An7j7EnH_sT9gpxr0sFevGHU5Ip3dQ?e=F9h3mx

Thanks.

**Comment by DarthMotzkus** [comment]
Nevermind, i got it working, i was converting on ULTRAISO and not saving.

Thanks!

**Comment by socram8888** [comment]
If anyone is reading this, note that in v1.4 modded games will be supported too.
