### ISSUE TITLE
Mizzurna Falls - Black Screen after New Game first FMV

### ISSUE THREAD

**Issue by DarthMotzkus** [socram8888/tonyhax#95]
Before opening this kind of issue, please ensure:
 - Are you using a compatible console version?
 YES
 - Are you using CD-R media, and not CD-RW?
 CD-R
 - Did you copy all the files in the expected format to the memory card?
 YES

**tonyhax version**: Which version are you running? Please ensure you are running the latest stable, or a newer beta.
1.4.1
**Installation method**: How did you get tonyhax on the memory card?
FREEPSXBOOT IMG
**Entry point game**: Which game are you using to launch tonyhax?
N/A
**Console model**: Console product code, written on the bottom of the unit, such as "SCPH-7502"
SCPH-102
**Integrity check**: If it boots, does the built-in integrity check succeed?
YES
**BIOS version**: If you can get to boot, which version of the BIOS does it report?
4.5
**Target game**: If the bug happens when launching a game, what's its name and game code? Example: "Spyro 3 (SCES-02835)"
MIZZURNA FALLS (SLPS-01783)

**Bug explanation**:
After hit new game, a FMV start, after it ends, the game stuck in black screen, no sound.

ISO: https://cdromance.com/psx-iso/mizzurna-falls-jpn/

Patched EUA Translated ISO: https://dl8.cdromance.com/download.php?file=Mizzurna%20Falls%20(English%20by%20Cirosan).7z&id=159606&platform=psx-iso&key=3364572576405

**Comment by DarthMotzkus** [comment]
Hi @socram8888, any news about this bug? Thanks!

**Comment by socram8888** [comment]
Sorry, I've moved [to other projects](https://lkml.org/lkml/2021/6/26/132) so this bug might take a while to get fixed.

**Comment by socram8888** [comment]
Okay I'm having a look right now and I can confirm this bug is present in tonyhax v1.4.1. Let's see why is this the case...

**Comment by socram8888** [comment]
Please try this version: [tonyhax-v1.4.2b.zip](https://github.com/socram8888/tonyhax/files/6760603/tonyhax-v1.4.2b.zip) (built from 95a3ed99ed4f5840440a252378de18c6dd1d4c13)

This crash was caused by an illegal opcode at 0x8000B104. This was odd and puzzled me because this is within the area of RAM reserved for the BIOS' heap, so the game had no business calling here. In fact, the original, Japanese version doesn't do this.

It turns this English translation is using a super hacky approach to gaining some extra space for their code.

The PSX-EXE headers are 2048 bytes but only 60-odd bytes of these are used, and the rest are zero. This translation team has decided to use this unused space for some extra code, and are exploiting the fact the BIOS loads this entire 2048-byte header to 0xA000B070 to insert some jumps scattered through the code to this fixed address.

Changing tonyhax to use this address as well for loading the executable header fixed this issue.

**Comment by DarthMotzkus** [comment]
Hi. Amazing man, worked flawlessly, and i loved the new slot 2 method for FreePSXBoot, no MC swaps anymore! Thanks for your time and dedication on this, helping the community and the whole scene of PSX. You are the best!

**Comment by socram8888** [comment]
This translation should be playable again with 8d69e31127303164086f63831caa78038271427f.

**Comment by dantesquivel** [comment]
> Please try this version: [tonyhax-v1.4.2b.zip](https://github.com/socram8888/tonyhax/files/6760603/tonyhax-v1.4.2b.zip) (built from [95a3ed9](https://github.com/socram8888/tonyhax/commit/95a3ed99ed4f5840440a252378de18c6dd1d4c13))
> 
> This crash was caused by an illegal opcode at 0x8000B104. This was odd and puzzled me because this is within the area of RAM reserved for the BIOS' heap, so the game had no business calling here. In fact, the original, Japanese version doesn't do this.
> 
> It turns this English translation is using a super hacky approach to gaining some extra space for their code.
> 
> The PSX-EXE headers are 2048 bytes but only 60-odd bytes of these are used, and the rest are zero. This translation team has decided to use this unused space for some extra code, and are exploiting the fact the BIOS loads this entire 2048-byte header to 0xA000B070 to insert some jumps scattered through the code to this fixed address.
> 
> Changing tonyhax to use this address as well for loading the executable header fixed this issue.

Hi - Sorry, I have no idea how to use the files you're pointing to. I'm using the bin cue pair in real hardware (BC PS3) and get the same black screen after the initial videa. How do I use the files you provided? I've tried both finding a pre-patched version and patching it myself and keep getting the same error.
